### ISSUE TITLE
Directive 'link' needs more variants

### ISSUE THREAD

**Issue by trikadin** [kobezzza/Snakeskin#26]
- link (rel = favicon)
  favicon.ico

=>

<link type="text/css" rel="stylesheet" rel="favicon" href="favicon.ico"/>

**Comment by trikadin** [comment]
&lt;link type="text/css" rel="stylesheet" rel="favicon" href="favicon.ico"/&gt;

**Comment by kobezzza** [comment]
Fixed in SS7:

```
link icon :: favicon.ico
```

or

```
link _ rel = icon | type = image/png :: favicon.png
```
